version: '3.9'

services:
  php:
    build:
      context: ./backend/docker/php
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    volumes:
      - ./backend:/var/www
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
